### ISSUE TITLE
Unable to import types

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/babylon-proto-ts#15]
npm install this lib in simple-staking, try import any of the types, error will be throw.

**Comment by jrwbabylonlab** [comment]
Put this ticket on hold as we discovered the protobuf might not needed at all

**Comment by gbarkhatov** [comment]
@jrwbabylonlab just to confirm - we do need them now, right?

**Comment by jrwbabylonlab** [comment]
yes. i will deal with it. will let you focus on the UI stuff
